### ISSUE TITLE
Open MiniApp in another web view

### ISSUE THREAD

**Issue by wanght** [Appboxo/ios-sdk-binary#1]
Integration has no problem, app run correctly, but when load mini app using: 
        let miniapp = Appboxo.shared.getMiniapp(appId: "app84436", authPayload: "payload")
        miniapp.delegate = self
        miniapp.open(viewController: self)
loading a mini app interface, and after that, it run the mini app in a new-created webview view controller, why???
my client id and appID is all correct. new vc below:
 
![image](https://user-images.githubusercontent.com/3711819/108803447-a3b58c00-75d5-11eb-868f-0bff08e29c17.png)

**Comment by azakush** [comment]
The problem was solved from our side, it was necessary to add a url to white listed urls. Closing the issue.
